version: "3.9"

services:
  mvn:
    image: maven:3.8-openjdk-11
    volumes:
      - .:/usr/src/mvn-tutorial
      - app-volume:/dist
    working_dir: /usr/src/mvn-tutorial
    command: bash -c "
        mvn clean install -q \
        && cp target/*.war /dist
      "
  web:
    build: .
    volumes:
      - app-volume:/opt/jboss/wildfly/standalone/deployments
    ports:
      - "8080:8080"
      - "3307:3306"
    depends_on:
      - mvn
volumes:
    app-volume: